title: Ananthakrishnan Narayanan, PhD
description: Reliability Leadership in the Era of AI
theme: jekyll-theme-slate

header_pages:
  - about.md
  - publications.md
  - patents.md
  - speaking.md
  - technical-engagement.md
  - contact.md
